name: Install dependencies, run lint, tests and build on merging to develop
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - name: run lint
        run: yarn lint
      - name: run tests
        run: yarn test --watchAll=false --coverage --reporters=default
      - name: build
        run: yarn build
